##
# Examples build script
##
Import('env')
# Add third party libraries
lib_env = env.Clone()
SConscript(env.get('SRC_DIR') + '/resource/third_party_libs.scons', 'lib_env')

ant_env = lib_env.Clone()

######################################################################
# Build flags
######################################################################
ant_env.AppendUnique(CPPPATH = [
		'../resource/include/',
		'../resource/csdk/stack/include',
		'../resource/csdk/ocsocket/include',
		'../resource/csdk/ocrandom/include',
		'../resource/csdk/logger/include',
		'../resource/csdk/libcoap',
		'../resource/oc_logger/include',
		'./virtual-sensor/common/inc',
		'./virtual-sensor/gateway-manager/inc',
		'./virtual-sensor/virtual-sensor-api/inc',
		])

ant_env.AppendUnique(CXXFLAGS = ['-g'])

target_os = env.get('TARGET_OS')
if target_os not in ['windows', 'winrt']:
	ant_env.AppendUnique(CXXFLAGS = ['-std=c++0x', '-Wall', '-lpthread'])

	# Note: 'pthread' is in libc for android. On other platform, if use
	# new gcc(>4.9?) it isn't required, otherwise, it's required
	if target_os != 'android':
		ant_env.AppendUnique(LIBS = ['-lpthread', '-ldl'])

ant_src = [
		'./virtual-sensor/gateway-manager/inc/sqlite3.c',
		'./virtual-sensor/gateway-manager/src/sql_wrapper.cpp'
]

libant = ant_env.StaticLibrary(
		target = 'libant',
		source = [ant_src]
		)
ant_env.InstallTarget(libant, 'libant')

ant_env.AppendUnique(LIBPATH = [env.get('BUILD_DIR')])
ant_env.PrependUnique(LIBS = ['oc', 'octbstack', 'coap', 'oc_logger', 'libant'])

if target_os == 'android':
	ant_env.AppendUnique(CXXFLAGS = ['-frtti', '-fexceptions'])
	ant_env.AppendUnique(LIBS = ['gnustl_static'])

	if not env.get('RELEASE'):
		ant_env.AppendUnique(LIBS = ['log'])

if target_os in ['darwin', 'ios']:
	ant_env.AppendUnique(CPPDEFINES = ['_DARWIN_C_SOURCE'])

######################################################################
# Source files and Targets
######################################################################
#sqltest = ant_env.Program('sqltest', 'sql_wrapper.cpp');

gateway = ant_env.Program('gateway', 
		['./virtual-sensor/gateway-manager/src/gw_spm.cpp',
		'./virtual-sensor/gateway-manager/src/gw_collection.cpp',
		'./virtual-sensor/gateway-manager/src/gw_lite_ss.cpp',
		'./virtual-sensor/gateway-manager/src/gw_sdm.cpp',
		'./virtual-sensor/gateway-manager/src/gw_interface.cpp',
		'gateway.cpp'])
mobileConsumerApp = ant_env.Program('mobileConsumerApp', 
		['./virtual-sensor/virtual-sensor-api/src/vs_basic.cpp',
		'./virtual-sensor/common/src/vs_utility.cpp',
		'mobileConsumerApp.cpp'])

# Physical Providers
IllumProvider = ant_env.Program('./providers_physical/IllumProvider',
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_physical/IllumProvider.cpp'])
PressAltProvider = ant_env.Program('./providers_physical/PressAltProvider', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_physical/PressAltProvider.cpp'])
TempHumidProvider = ant_env.Program('./providers_physical/TempHumidProvider',
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_physical/TempHumidProvider.cpp'])
ProvTempHumi = ant_env.Program('ProvTempHumi', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_physical/provTempHumi.cpp'])

# Simulated Providers
SimulBathLight1 = ant_env.Program('./providers_simul/SimulBathLight1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulBathLight1.cpp'])
SimulBathMotion1 = ant_env.Program('./providers_simul/SimulBathMotion1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulBathMotion1.cpp'])
SimulBathOutlet1 = ant_env.Program('./providers_simul/SimulBathOutlet1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulBathOutlet1.cpp'])
SimulBathOutlet2 = ant_env.Program('./providers_simul/SimulBathOutlet2', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulBathOutlet2.cpp'])
SimulBedLight1 = ant_env.Program('./providers_simul/SimulBedLight1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulBedLight1.cpp'])
SimulBedMotion1 = ant_env.Program('./providers_simul/SimulBedMotion1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulBedMotion1.cpp'])
SimulBedOutlet1 = ant_env.Program('./providers_simul/SimulBedOutlet1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulBedOutlet1.cpp'])
SimulBedOutlet2 = ant_env.Program('./providers_simul/SimulBedOutlet2', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulBedOutlet2.cpp'])
SimulBedPressure = ant_env.Program('./providers_simul/SimulBedPressure', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulBedPressure.cpp'])
SimulDoorDoor = ant_env.Program('./providers_simul/SimulDoorDoor', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulDoorDoor.cpp'])
SimulDoorLight1 = ant_env.Program('./providers_simul/SimulDoorLight1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulDoorLight1.cpp'])
SimulDoorMotion1 = ant_env.Program('./providers_simul/SimulDoorMotion1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulDoorMotion1.cpp'])
SimulGearHeart = ant_env.Program('./providers_simul/SimulGearHeart', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulGearHeart.cpp'])
SimulGearMotion = ant_env.Program('./providers_simul/SimulGearMotion', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulGearMotion.cpp'])
SimulIllum = ant_env.Program('./providers_simul/SimulIllum', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulIllum.cpp'])
SimulKitchenInfrared = ant_env.Program('./providers_simul/SimulKitchenInfrared', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulKitchenInfrared.cpp'])
SimulKitchenLight1 = ant_env.Program('./providers_simul/SimulKitchenLight1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulKitchenLight1.cpp'])
SimulKitchenMotion1 = ant_env.Program('./providers_simul/SimulKitchenMotion1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulKitchenMotion1.cpp'])
SimulKitchenOutlet1 = ant_env.Program('./providers_simul/SimulKitchenOutlet1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulKitchenOutlet1.cpp'])
SimulKitchenValve = ant_env.Program('./providers_simul/SimulKitchenValve', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulKitchenValve.cpp'])
SimulLivingDamp1 = ant_env.Program('./providers_simul/SimulLivingDamp1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulLivingDamp1.cpp'])
SimulLivingDamp2 = ant_env.Program('./providers_simul/SimulLivingDamp2', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulLivingDamp2.cpp'])
SimulLivingLight1 = ant_env.Program('./providers_simul/SimulLivingLight1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulLivingLight1.cpp'])
SimulLivingLight2 = ant_env.Program('./providers_simul/SimulLivingLight2', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulLivingLight2.cpp'])
SimulLivingMotion1 = ant_env.Program('./providers_simul/SimulLivingMotion1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulLivingMotion1.cpp'])
SimulLivingOutlet1 = ant_env.Program('./providers_simul/SimulLivingOutlet1', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulLivingOutlet1.cpp'])
SimulLivingOutlet2 = ant_env.Program('./providers_simul/SimulLivingOutlet2', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulLivingOutlet2.cpp'])
SimulLivingOutlet3 = ant_env.Program('./providers_simul/SimulLivingOutlet3', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulLivingOutlet3.cpp'])
SimulLivingPhone = ant_env.Program('./providers_simul/SimulLivingPhone', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulLivingPhone.cpp'])
SimulLivingPressure = ant_env.Program('./providers_simul/SimulLivingPressure', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulLivingPressure.cpp'])
SimulLumoPosture = ant_env.Program('./providers_simul/SimulLumoPosture', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulLumoPosture.cpp'])
SimulTempHumi = ant_env.Program('./providers_simul/SimulTempHumi', 
		['./virtual-sensor/gateway-manager/src/phy_interface.cpp',
		'./providers_simul/SimulTempHumi.cpp'])

Alias("ant",
		[gateway, mobileConsumerApp])
env.AppendTarget('ant')
